behaviors:
  RollBlock:
    trainer_type: ppo
    keep_checkpoints: 5
    max_steps: 15000000
    time_horizon: 300 # Increased time horizon as task is long in 3D
    summary_freq: 60000

    hyperparameters:
      # Common Hyperparameters
      batch_size: 400
      buffer_size: 14000 # Fits 20 batches of 512, large buffer causes failure
      learning_rate: 0.0001
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      beta: 0.001 # Decrease beta to decrease randomness (entropy) in actions (0.005 before) - Many papers choose 0 here as well
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95 # How much future rewards are discounted (0.95 before)
      num_epoch: 3

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: resnet
      normalize: true
      hidden_units: 300
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

environment_parameters:

  # Block Randomization
  spawn_extents_x: # This doesn't work for some reason
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.25
        max_value: 0.25
  spawn_extents_z: # This doesn't work for some reason
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.225
        max_value: 0.225
  block_euler_y:
    sampler_type: uniform
    sampler_parameters:
        min_value: -18.0
        max_value: 18.0
  tool_position_noise_x:
    sampler_type: uniform
    sampler_parameters:
        min_value: -0.2575
        max_value: 0.2575
  tool_position_noise_y:
    sampler_type: uniform
    sampler_parameters:
        min_value: -0.04
        max_value: 0.04
  tool_position_noise_z:
    sampler_type: uniform
    sampler_parameters:
        min_value: -0.07
        max_value: 0.17
  block_friction:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.10
      max_value: 0.12
  block_scale_x:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.50
        max_value: 0.53
  block_scale_y:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.10
        max_value: 0.115
  block_scale_z:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.10
        max_value: 0.115
  block_mass:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.0004
        max_value: 0.0009
  block_color_v:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.05
        max_value: 0.18
  block_side_color_r:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.42
        max_value: 0.72
  block_side_color_g:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.0
        max_value: 0.2

  # Floor Position and Inclination
  ground_py_noise:
    sampler_type: uniform
    sampler_parameters:
        min_value: -0.05
        max_value: 0.05
  ground_angle_x:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0
        max_value: 15

  # Floor Randomization
  ground_r:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.65
        max_value: 1.0
  ground_g:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.9
        max_value: 1.0
  ground_b:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.9
        max_value: 1.0
  dynamic_friction:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.33
        max_value: 0.33 # Keep this not randomized
  static_friction:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.33
        max_value: 0.33 # Keep this not randomized

  # Camera Randomization
  # Side
  camera_px:
    sampler_type: uniform
    sampler_parameters:
        min_value: -1.5
        max_value: -1.15
  camera_py:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.9
        max_value: 1.22
  camera_pz:
    sampler_type: uniform
    sampler_parameters:
        min_value: -1.27
        max_value: -1.07
  camera_rx:
    sampler_type: uniform
    sampler_parameters:
        min_value: 26
        max_value: 33
  camera_ry:
    sampler_type: uniform
    sampler_parameters:
        min_value: 86.0
        max_value: 94.0

  # PointLightTop Randomization
  light_intensity:
    sampler_type: uniform
    sampler_parameters:
        min_value: 10
        max_value: 50
  light_px:
    sampler_type: uniform
    sampler_parameters:
        min_value: -3.8
        max_value: -1.8
  light_py:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.5
        max_value: 3.5
  light_pz:
    sampler_type: uniform
    sampler_parameters:
        min_value: -3.5
        max_value: -0.8
  less_than_point_five_no_shadow:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.0
        max_value: 1.0