behaviors:
  RollBlock:
    trainer_type: ppo
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 256 
    summary_freq: 60000

    hyperparameters:
      # Common Hyperparameters
      batch_size: 256 
      buffer_size: 10240
      learning_rate: 0.0001
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      beta: 0.001
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3

    network_settings:
      vis_encode_type: resnet
      normalize: true
      hidden_units: 256
      num_layers: 2
      memory:
        sequence_length: 64
        memory_size: 256

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

environment_parameters:

  block_euler_y:
    sampler_type: uniform
    sampler_parameters:
      min_value: -10
      max_value: 10
  tool_position_noise_x:
    sampler_type: uniform
    sampler_parameters:
      min_value: -0.03
      max_value: 0.03
  tool_position_noise_y:
    sampler_type: uniform
    sampler_parameters:
      min_value: -0.04
      max_value: 0.04
  tool_position_noise_z:
    sampler_type: uniform
    sampler_parameters:
      min_value: -0.05
      max_value: 0.05
    
  block_friction:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.1
      max_value: 0.2
  scale:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.3
        max_value: 0.5
  mass:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.1
        max_value: 0.3
  block_r:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.5
        max_value: 1.0
  target_rb:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.25
        max_value: 0.75

  # Floor Randomization
  ground_r:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.0
        max_value: 0.4
  ground_g:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.8
        max_value: 1.0
  ground_b:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.8
        max_value: 1.0

  # Camera Randomization
  camera_px:
    sampler_type: uniform
    sampler_parameters:
        min_value: -3.05
        max_value: -2.95
  camera_py:
    sampler_type: uniform
    sampler_parameters:
        min_value: 2.95
        max_value: 3.05
  camera_pz:
    sampler_type: uniform
    sampler_parameters:
        min_value: -0.05
        max_value: 0.05
  camera_rx:
    sampler_type: uniform
    sampler_parameters:
        min_value: 43.0
        max_value: 47.0
  camera_ry:
    sampler_type: uniform
    sampler_parameters:
        min_value: 89.5
        max_value: 91.5
  camera_rz:
    sampler_type: uniform
    sampler_parameters:
        min_value: -1.5
        max_value: 1.5

  # Light Randomization
  light_intensity:
    sampler_type: uniform
    sampler_parameters:
        min_value: 10
        max_value: 40
  light_px:
    sampler_type: uniform
    sampler_parameters:
        min_value: -3
        max_value: 3
  light_py:
    sampler_type: uniform
    sampler_parameters:
        min_value: 4
        max_value: 7
  light_pz:
    sampler_type: uniform
    sampler_parameters:
        min_value: -2
        max_value: 0.6
  shadow_probability:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.0
        max_value: 1.0
