behaviors:
  CutRope:
    trainer_type: ppo
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 60000

    hyperparameters:
      # Common Hyperparameters
      batch_size: 256 
      buffer_size: 10240
      learning_rate: 0.0003
      learning_rate_schedule: linear
      
      # PPO-specific hyperparameters
      beta: 0.005
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
    
    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: resnet
      normalize: true
      hidden_units: 128
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

environment_parameters:
  # Lighting Randomization
  light_intensity:
    sampler_type: uniform
    sampler_parameters:
        min_value: 10
        max_value: 40
  light_px:
    sampler_type: uniform
    sampler_parameters:
        min_value: -3
        max_value: 3
  light_py:
    sampler_type: uniform
    sampler_parameters:
        min_value: 4
        max_value: 7
  light_pz:
    sampler_type: uniform
    sampler_parameters:
        min_value: -2
        max_value: 1.5
  shadow_probability:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0
      max_value: 1

  # Rope Randomization
  rope_thickness:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.015
        max_value: 0.025
  rope_sag:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.97
        max_value: 1.05

  # Camera Randomization
  camera_px:
    sampler_type: uniform
    sampler_parameters:
        min_value: -0.05
        max_value: 0.05
  camera_py:
    sampler_type: uniform
    sampler_parameters:
        min_value: 2.15
        max_value: 2.25
  camera_pz:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0.1
        max_value: 0.2
  camera_rx:
    sampler_type: uniform
    sampler_parameters:
        min_value: 43
        max_value: 47
  camera_ry:
    sampler_type: uniform
    sampler_parameters:
        min_value: -1.5
        max_value: 1.5
  camera_rz:
    sampler_type: uniform
    sampler_parameters:
        min_value: -1.5
        max_value: 1.5

  # Camera Randomization
  tool_position_noise_x:
    sampler_type: uniform
    sampler_parameters:
        min_value: -0.3
        max_value: 0.3
  tool_position_noise_y:
    sampler_type: uniform
    sampler_parameters:
        min_value: -0.1
        max_value: 0.1

  # Color Randomizations
  ground_g:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.7
      max_value: 0.85

  mount_g:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.75
      max_value: 0.85

  rope_r:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.8
      max_value: 1.0

  marker_r:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.7
      max_value: 1.0

  x_tiling:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.85
      max_value: 1.4
  y_tiling:
    sampler_type: uniform
    sampler_parameters:
      min_value: 1.0
      max_value: 3.0

  tool_gripper_r:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.3
      max_value: 0.6

  # tool roll (repeated rgb)
  tool_roll_r:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.0
      max_value: 0.15

  # tool shaft (repeated rgb)
  tool_shaft_r:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.05
      max_value: 0.25
