using UnityEngine;
using UnityEngine.Networking;
using System.Collections;

public class H1ActionGenerator : MonoBehaviour
{
    public SceneDescriptor sceneDescriptor;

    public Main main;

    public string output;
    public string promptTemplate;
    public string h0_actions_descriptions;
    public string state_change_def;

    private void Start()
    {

        output = "";

        promptTemplate = @"
            We define a H0 level of robot control functions. These include the following:
            {h0_actions_descriptions}

            Here is the scene description for a task in JSON format.

            {scene_description}

            Single State Change: {single_state_change}

            An H1 level function is one that is composed of a sequence of H0 level functions.
            Come up with H1 level function(s) that represent a single state change for this scene.
            Provide code in C# that should only include calls to H0 level functions.
            Ensure you also add a docstring for each of the function you generate with details on what the function does and what each parameter means clearly.
            These functions should be generic, i.e., should not specify any specific scene object.
            Any input to H0 level functions should be input to the H1 function using them.
            Remove any input to H1 level function(s) that doesn't get used in H0 level function(s).

            Make sure to wrap all the function definitions within a ```start_flag and ```end_flag for parsing purposes.
            Only give the function definition without wrapping it inside any class and assume H0 functions have already been defined.
            Assume the functions take string inputs.
            
            Additionally, make sure to represent each H1 function to its sequence of H0 functions with its parameters as comma separated of the format.
            If multiple function definitions exit, repsent each mapping by comma separated. Only include the function signature and any parameters as strings in this.
            The format is given below:

            H1_function() = [H0_func1(), H0_func2(), H0_func3()].

            It is important to remember that in the function call signature, any parameters that are not used in the function should be removed.
            Do NOT include any type for parameters, just the parameter names as strings, where each parameter is ONE SINGLE string in the function signature.

            Wrap ALL the functions generated by comma separated in tag ```start_mapping and ```end_mapping flags for parsing purposes.
            It it important that all the generated functions should come inside a single ```start_mapping and ```end_mapping flag being commma separated
            instead of each function having its own flag.
            
            ";

        state_change_def = "For this scene, we consider moving a hoop from one pillar to another as a state change.";

        h0_actions_descriptions = @"
            MoveCoroutine(reachable_object): Move robot arm above 'REACHABLE' input object. Objects not reachable cannot be passed as input.
            GrabCoroutine(): Pick up top 'GRABBABLE' object below current position. Objects not GRABBABLE cannot be passed as input.
            DropCoroutine(): Drop picked up object at current position.
            PushCoroutine(final_dest): Push object at current position to specified position.
            RollCoroutine(direction): Roll object at current position in specified direction.
            CutCoroutine(): Cut top object below current position.
        ";
    }


    public IEnumerator generateH1Actions()
    {
        string sceneDescriptionJSON = sceneDescriptor.output;

        if (sceneDescriptor.output == "")
        {
           Debug.Log("[SceneDescriptor] -- Please ensure you generate an output from scene descriptor VLM by calling generate()");
           yield break;
        }


        // string sceneDescriptionJSON = @"
        // {
        //     ""objects"": [
        //         ""<peg_green>"",
        //         ""<hoop_yellow>"",
        //         ""<hoop_white>"",
        //         ""<hoop_purple>"",
        //         ""<peg_red>"",
        //         ""<peg_blue>""
        //     ],
        //     ""object_properties"": {
        //         ""<peg_green>"": [],
        //         ""<hoop_yellow>"": [""GRABBABLE""],
        //         ""<hoop_white>"": [""GRABBABLE""],
        //         ""<hoop_purple>"": [""GRABBABLE""],
        //         ""<peg_red>"": [],
        //         ""<peg_blue>"": []
        //     },
        //     ""spatial_relations"": {
        //         ""<peg_green>"": [],
        //         ""<hoop_yellow>"": [""in(<peg_green>)"", ""above(<hoop_white>)""],
        //         ""<hoop_white>"": [""in(<peg_green>)"", ""above(<hoop_purple>)""],
        //         ""<hoop_purple>"": [""in(<peg_green>)""],
        //         ""<peg_red>"": [],
        //         ""<peg_blue>"": []
        //     },
        //     ""your_explanation"": ""I included three hoops (yellow, white, purple) that are on the green peg, along with two additional pegs (red and blue). Each hoop is in the green peg, and the yellow hoop is above the white, which is above the purple, showing their stacked order. There are no other objects in the scene.""
        // }";


        string prompt = promptTemplate.Replace("{scene_description}", sceneDescriptionJSON).Replace("{h0_actions_descriptions}", h0_actions_descriptions).Replace("{single_state_change}", state_change_def);

        // StartCoroutine(CallDeepSeekAPI(prompt));

        yield return StartCoroutine(CallOpenAIAPI(prompt));
        
    }

    IEnumerator CallOpenAIAPI(string prompt)
    {
        string APIKey = main.getOpenAIAPIKey();
        string APIurl = main.getOpenAIAPIURL();

        // Escape prompt string for JSON
        string escapedPrompt = prompt.Replace("\\", "\\\\")
                                            .Replace("\"", "\\\"")
                                            .Replace("\n", "\\n")
                                            .Replace("\r", "\\r");

        // Build JSON request body
        string jsonRequest = $@"{{
            ""model"": ""o4-mini"",
            ""messages"": [
                {{
                    ""role"": ""system"",
                    ""content"": ""You are an action generator VLM at a hierarchy level of H1 for given user instruction.""
                }},
                {{
                    ""role"": ""user"",
                    ""content"": ""{escapedPrompt}""
                }}
            ],
            ""max_completion_tokens"": 3000
        }}";

        UnityWebRequest request = new UnityWebRequest(APIurl, "POST");
        byte[] bodyRaw = System.Text.Encoding.UTF8.GetBytes(jsonRequest);
        request.uploadHandler = new UploadHandlerRaw(bodyRaw);
        request.downloadHandler = new DownloadHandlerBuffer();

        request.SetRequestHeader("Content-Type", "application/json");
        request.SetRequestHeader("Authorization", $"Bearer {APIKey}");

        Debug.Log("[H1ActionGenerator] Sending OpenAI API Request...");
        yield return request.SendWebRequest();
        Debug.Log("[H1ActionGenerator] Received API Response.");

        if (request.result != UnityWebRequest.Result.Success)
        {
            Debug.LogError($"[H1ActionGenerator] API Request Failed: {request.error}\n{request.downloadHandler.text}");
        }
        else
        {
            string jsonResponse = request.downloadHandler.text;

            OpenAIResponse response = JsonUtility.FromJson<OpenAIResponse>(jsonResponse);

            Debug.Log("[H1ActionGen] Raw API response:\n" + jsonResponse);

            if (response.choices != null && response.choices.Length > 0)
            {
                string content_output = response.choices[0].message.content.Trim();
                Debug.Log("[H1ActionGenerator] OpenAI Output:\n" + content_output);

                output = main.ExtractBetweenFlags(content_output);

                string functionMappingLine = main.ExtractBetweenFlags(content_output, "```start_mapping", "```end_mapping");
                main.ParseHierarchicalFunctionMappings(functionMappingLine);

                Debug.Log("EXTRACTED DATA ");
                Debug.Log(output);

                // H1 → H0
                Debug.Log("======== H1 to H0 Mapping ========");
                foreach (var kv in main.h1Toh0Mapping)
                {
                    Debug.Log($"H1: {kv.Key} => H0 Calls: [{string.Join(", ", kv.Value)}]");
                }

                // H2 → H1
                Debug.Log("======== H2 to H1 Mapping ========");
                foreach (var kv in main.h2Toh1Mapping)
                {
                    Debug.Log($"H2: {kv.Key} => H1 Calls: [{string.Join(", ", kv.Value)}]");
                }

                // Function Param Signatures
                Debug.Log("======== Function Param Signatures ========");
                foreach (var kv in main.functionParamSignature)
                {
                    Debug.Log($"{kv.Key} params: ({string.Join(", ", kv.Value)})");
                }

                // Full Calls With Args
                Debug.Log("======== Calls With Args ========");
                foreach (var kv in main.functionToCallsWithArgs)
                {
                    Debug.Log($"{kv.Key} => [{string.Join(", ", kv.Value)}]");
                }


            }
            else
            {
                Debug.LogError("[H1ActionGen] OpenAI API returned empty choices or malformed response.");
            }
        }
    }

    // Response wrapper for JsonUtility
    [System.Serializable]
    private class OpenAIResponse
    {
        public Choice[] choices;
    }

    [System.Serializable]
    private class Choice
    {
        public Message message;
    }

    [System.Serializable]
    private class Message
    {
        public string role;
        public string content;
    }

    //IEnumerator CallDeepSeekAPI(string promptContent)
    //{
    //    string jsonRequest = $@"{{
    //        ""model"": ""deepseek-reasoner"",
    //        ""messages"": [
    //            {{
    //                ""role"": ""user"",
    //                ""content"": ""{promptContent.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r")}""
    //            }}
    //        ],
    //        ""temperature"": 0.1,
    //        ""max_tokens"": 1500
    //    }}";

    //    UnityWebRequest request = new UnityWebRequest(APIurl, "POST");
    //    byte[] bodyRaw = System.Text.Encoding.UTF8.GetBytes(jsonRequest);
    //    request.uploadHandler = new UploadHandlerRaw(bodyRaw);
    //    request.downloadHandler = new DownloadHandlerBuffer();

    //    request.SetRequestHeader("Content-Type", "application/json");
    //    request.SetRequestHeader("Authorization", $"Bearer {APIKey}");

    //    Debug.Log("Sending API Request");
    //    yield return request.SendWebRequest();
    //    Debug.Log("Received API Response");
    //    if (request.result != UnityWebRequest.Result.Success)
    //    {
    //        Debug.LogError($"API Request Failed: {request.error}\n{request.downloadHandler.text}");
    //    }
    //    else
    //    {
    //        string jsonResponse = request.downloadHandler.text;

    //        DeepSeekResponse response = JsonUtility.FromJson<DeepSeekResponse>(jsonResponse);

    //        if (response.choices != null && response.choices.Length > 0)
    //        {
    //            output = response.choices[0].message.content.Trim();
    //            Debug.Log("DeepSeek Reasoner Output:\n" + output);
    //        }
    //        else
    //        {
    //            Debug.LogError("DeepSeek API returned empty choices or malformed response.");
    //        }
    //    }
    //}

    //// Response wrappers for JsonUtility
    //[System.Serializable]
    //private class DeepSeekResponse
    //{
    //    public Choice[] choices;
    //}

    //[System.Serializable]
    //private class Choice
    //{
    //    public Message message;
    //}

    //[System.Serializable]
    //private class Message
    //{
    //    public string role;
    //    public string content;
    //}
}
