<package format="2">
  <name>psm_models</name>
  <version>1.0.0</version>
  <description>dVRK PSM Models</description>
  <license>BSD-3</license>
  <author email="mhaid@cs.toronto.edu">Mustafa Haiderbhai</author>
  <maintainer email="mhaid@cs.toronto.edu">Mustafa Haiderbhai</maintainer>
  <buildtool_depend>catkin</buildtool_depend>
  <test_depend>roslaunch</test_depend>
</package>