behaviors:
  TensionCutRope:
    trainer_type: ppo
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 60000

    hyperparameters:
      # Common Hyperparameters
      batch_size: 256 
      buffer_size: 10240
      learning_rate: 0.0003
      learning_rate_schedule: linear
      
      # PPO-specific hyperparameters
      beta: 0.005
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
    
    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: resnet
      normalize: true
      hidden_units: 256
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0