using UnityEngine;

// This file contains all h1 and h2 actions generated by VLM. Ideally we will have it write to this file dynamically or we can copy paste
public class ActionDefinitions : MonoBehaviour
{
    // [TODO]: Drag the LowLevelMotor Controller from Interface
    public LowLevelMotor motor;

    // [TODO] Drag instance from Unity
    // This is the main driver file that has H1 Actions and UserInstructions defined in it.
    public Main main;

    public void MoveHoop(string sourcePillar, string targetPillar)
    {
        int sourcePillarNum = main.MapPillarNameToNum(sourcePillar.ToLower());
        int targetPillarNum = main.MapPillarNameToNum(targetPillar.ToLower());

        motor.MoveCoroutine(sourcePillarNum); // Move above the source pillar
        motor.GrabCoroutine();  // Pick up the top grabbable hoop
        motor.MoveCoroutine(targetPillarNum);  // Move above the target pillar
        motor.DropCoroutine(); // Drop the hoop onto the target pillar
    }

    /*** H2 Functions ***/
    public void SwapHoops(string pillar1, string pillar2, string tempPillar)
    {
        MoveHoop(pillar1, tempPillar);
        MoveHoop(pillar2, pillar1);
        MoveHoop(tempPillar, pillar2);
    }

    public void MoveLowerHoop(string sourcePillar, string targetPillar, string tempPillar)
    {
        MoveHoop(sourcePillar, tempPillar);
        MoveHoop(sourcePillar, targetPillar);
        MoveHoop(tempPillar, targetPillar);
    }
}
